Draft: add script to call IBM webhook
redhat-openshift-ecosystem/operator-pipelines-images pull request #30
Opened 2021-09-23 05:42 UTC by wcheang

2021-09-23 18:42 UTC, wcheang commented
The files under `webhook` were provided by Zach, and therefore excluded from the unit tests, and probably don't really need to be reviewed. I asked about whether there'll be a release so we could leverage that code as a library but it sounds like that's not the priority right now, and I was advised to just copy/paste them into our code repo since it's unlikely to change.

2021-10-18 19:58 UTC, amisstea requested changes

2021-10-18 19:58 UTC, amisstea commented on operatorcert/entrypoints/marketplace_replication.py
> +    if not marketplace_repo_regex.match(args.git_repo_url):
Each of our submission repos has the `organization` defined in its `config.yaml` ([example](https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators-preprod/blob/stage/config.yaml#L4)). Can we parse that instead? We can then drop the `git-repo-url` arg.

2021-10-18 19:58 UTC, amisstea commented on operatorcert/entrypoints/marketplace_replication.py
> +        "organization": "redhat-marketplace",
This could be passed straight from the `config.yaml` as I mentioned in my other comment.

2021-10-18 19:58 UTC, amisstea commented on operatorcert/entrypoints/marketplace_replication.py
> +            verify=False,
Can you make this configurable via a CLI arg to make it easier for testing?

2021-10-19 06:43 UTC, Allda approved these changes

2021-10-19 17:29 UTC, merged